### ISSUE TITLE
MNIST.swift:2:8: error: no such module 'Python'

### ISSUE THREAD

**Issue by wangw42** [huan/swift-MNIST#2]
```
Installing packages:
	.package(url: "https://github.com/huan/swift-MNIST", from: "0.4.0")
		MNIST
With SwiftPM flags: []
Working in: /tmp/tmp4dltfx2x/swift-install
[1/4] Compiling MNIST MNIST.swift
/content/swift-install/package/.build/checkouts/swift-MNIST/Sources/MNIST/MNIST.swift:2:8: error: no such module 'Python'
import Python
       ^
Install Error: swift-build returned nonzero exit code 1.
```

**Comment by huan** [comment]
I guess you are using the standard Swift when you get this error message.

Swift for TensorFlow needs to be installed first before you can use TensorFlow with Swift.

Read <https://github.com/tensorflow/swift/blob/master/Installation.md> for how to install it.

And you can use my Docker Image if you prefer to use docker run: <https://hub.docker.com/r/zixia/swift>

**Comment by wangw42** [comment]
Solved, thanks!

**Comment by huan** [comment]
You are welcome!

May I ask you what task are you working on using the swift for TensorFlow?

**Comment by wangw42** [comment]
lol, I just started learning swift for TensorFlow with [简单粗暴 TensorFlow 2](https://tf.wiki/index.html), and I'm not sure what task will I use it.

**Comment by huan** [comment]
Got it. So I hope you enjoy your studying with our TF.wiki!
